Fix docker build composer
forkcms/forkcms pull request #3229
Opened 2020-11-14 18:51 UTC by jessedobbelaere

## Type

- Non critical bugfix

## Resolves the following issues

## Pull request description

2 issues:

Composer.lock is outdated
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
```

`--no-suggest` is deprecated in composer v2 and removed in composer v3

```
Step 15/19 : RUN composer install --prefer-dist --no-dev --no-autoloader --no-scripts --no-progress --no-suggest &&     composer clear-cache
 ---> Running in 09ecbc21bef9
You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
```

2020-11-14 18:52 UTC, carakas approved these changes

2020-11-14 18:53 UTC, carakas requested changes
Hmm, I wonder what happend there with all those test packages dissapearing from require-dev

2020-11-14 19:13 UTC, jessedobbelaere commented
Maybe because of a newer phpstan versions @carakas ? I only ran `composer update phpstan/phpstan phpstan/phpstan-symfony --no-scripts` on current master to fix the outdated lock

2020-12-04 20:16 UTC, carakas approved these changes

2020-12-04 20:16 UTC, merged