Offline page
forkcms/forkcms pull request #3376
Opened 2021-04-22 12:20 UTC by bjorvack

## Type

- Feature

## Pull request description

Adds service worker for offline page
Internal reference https://app.activecollab.com/108877/reports/team-timeline?modal=Task-84793-62

2021-04-23 07:00 UTC, Katrienvh requested changes

2021-04-23 19:32 UTC, carakas commented
@bjorvack can you include a screenshot or something so we can see what it looks like?

2021-04-23 19:53 UTC, carakas requested changes

2021-04-23 19:53 UTC, carakas commented on app/Kernel.php
> +        defined('OFFLINE_PATH') || define('OFFLINE_PATH', PATH_WWW . '/offline');
We are working on getting those constants out, not a fan of adding new ones

2021-04-23 19:53 UTC, carakas commented on offline/.gitignore
> +*
why is this here? You have a file in that directory called offline.html but you are also telling git to ignore it?

2021-04-23 19:53 UTC, carakas commented on offline/offline.html
> +<!doctype html>
why a html page like this? Would it not be possible to include it in the cms? so the text won't need to be hardcoded?

2021-04-23 19:53 UTC, carakas commented on offline/offline.html
> +  <meta name="author" content="Sarah Meysman">
I would remove this line

2021-04-23 19:53 UTC, carakas commented on offline/offline.html
> +      <h1>You're offline</h1>
wouldnt it be possible to use the translation system so these text are in the language you are visiting the site?

2021-04-23 19:53 UTC, carakas commented on package-lock.json
> +  "packages": {
why is there suddenly so much npm stuff here? seems to contain a bunch of things that arent related

2021-04-23 19:53 UTC, carakas commented on src/Backend/Modules/Pages/Actions/Settings.php
> +            BACKEND_MODULES_PATH . '/' . $this->getModule() .'/Layout/Templates/Offline.html.twig',
wouldn't it make more sense to put this in the frontend? That way you can also override it in your theme

2021-04-23 19:53 UTC, carakas commented on src/Backend/Modules/Pages/Actions/Settings.php
> +        $offlinePage = fopen(OFFLINE_PATH . '/offline_' . Language::getWorkingLanguage() . '.html', 'w');
Please use Filesystem  dump of symfony for this.
Looks like the page is generated but you committed the generated code. Can you have a look at removing it?
Is this also enabled by default? If so if it generated when installing fork?

2021-04-23 19:53 UTC, carakas commented on src/Backend/Modules/Pages/Domain/Page/SettingsDataTransferObject.php
> +    const MODULE = 'Pages';
not a big fan of doing this

2021-04-23 19:53 UTC, carakas commented on src/Backend/Modules/Pages/Domain/Page/SettingsDataTransferObject.php
> +            $this::MODULE,
why $this and not self if you use this?

2021-04-23 19:53 UTC, carakas commented on src/Backend/Modules/Pages/Domain/Page/SettingsDataTransferObject.php
> +    const MODULE = 'Pages';
Please also add public protected or private if you do this

2021-04-23 19:53 UTC, carakas commented on src/Backend/Modules/Pages/Layout/Templates/Offline.html.twig
> +  <title>Offline page</title>
Use {{title}} here as well

2021-04-23 19:53 UTC, carakas commented on src/Backend/Modules/Pages/Layout/Templates/Offline.html.twig
> +  <meta name="author" content="Sarah Meysman">
Remove those two lines please

2021-04-23 19:53 UTC, carakas commented on src/Backend/Modules/Pages/Layout/Templates/Offline.html.twig
> +  <link href="/src/Frontend/Themes/Fork/Core/Layout/Css/screen.css?m=1593680880" rel="stylesheet" />
You should load the css in a proper way, you hardcoded the theme and the timestamp

2021-04-23 19:53 UTC, carakas commented on src/Frontend/Core/Header/Header.php
> +        $this->addJS('/src/Frontend/Modules/Pages/Js/Pages.js', true, true, Priority::module());
Not a fan of this, include it in the ES6 instead of this way.

2021-08-18 05:18 UTC, carakas commented
@bjorvack could you have a look at the feedback please?

2023-07-31 19:56 UTC, carakas commented
Closing stale PR, let me know if you want to finish the feedback

2023-07-31 19:56 UTC, closed without merging