WIP: Initialize ProfilesSessionIdChanged event
forkcms/forkcms pull request #3377
Opened 2021-04-24 12:49 UTC by wouterverstuyf

## Type
- Enhancement

## Resolves the following issues
When a public profile login/logout the session id changes.
Could be handy for other modules to hook in through an event, to get the new Session ID.

## Pull request description
This PR initializes the Event in the Profiles module, I built this based on the Formbuilder Event. Not sure it's the right way, I've given it a shot but help is much appreciated.
I just added the dispatcher in the Login function. If this works it should also be applied to the Logout function.

Next thing/question => How to use this event in other modules?
I ended up with the following but I suppose there is something more to do, because the Listener don't catch the event.

/Frontend/Modules/<MyModule>/EventListener/ProfilesSessionIdChangedListener.php
<pre>
namespace Frontend\Modules\<MyModule>\EventListener;

use Frontend\Modules\Profiles\Event\ProfilesSessionIdChangedEvent;

class ProfilesSessionIdChangedListener
{
    public function __construct()
    {
        \spoon::dmp('I am listening...');

    }
    public function onProfilesSessionIdChanged(ProfilesSessionIdChangedEvent $event): void
    {
        $event->getSessionId();
    }
}
</pre>

What are the steps to add a listener (that works :)) in another module?
Anyone wanna help? :)
Thx!

2021-04-26 04:24 UTC, wouterverstuyf commented
Question : when you login/logout in the backend section, the Session ID also changes. Should this be event be triggered from the backend login/logout function also? Is it ok to trigger a frontend event from within the backend section?

2021-04-26 07:43 UTC, carakas commented
@wouterverstuyf I would add it in the Common namespace, not in the profiles one. It is tied to the session, not a profile

2021-04-26 07:44 UTC, carakas commented on src/Frontend/Modules/Profiles/Engine/Authentication.php
> +        $oldSession = FrontendModel::getSession()->getId();
you can use $session->getId() here

2021-04-26 07:45 UTC, wouterverstuyf commented
> @wouterverstuyf I would add it in the Common namespace, not in the profiles one. It is tied to the session, not a profile, and then you can throw the event in the backend as well

Yes, got the same feeling this morning, I check it ;)

2021-04-26 07:45 UTC, carakas requested changes

2021-04-26 07:45 UTC, carakas commented on src/Frontend/Modules/Profiles/Event/ProfilesSessionIdChangedEvent.php
> +        $this->sessionId = FrontendModel::getSession()->getId();
Pass this one in the constructor as well.

2021-05-03 06:22 UTC, carakas approved these changes

2021-05-03 06:23 UTC, merged