Fixed php 8.0 support
forkcms/forkcms pull request #3538
Opened 2022-12-05 08:59 UTC by jacob-v-dam

## Type

- Critical bugfix
- Non critical bugfix
- Enhancement
- Feature

## Resolves the following issues

## Pull request description

2023-02-20 08:33 UTC, carakas requested changes

2023-02-20 08:33 UTC, carakas commented on .github/workflows/run-tests.yml
> +                php: [7.4]
Can you add the php 8 versions here as well

2023-07-26 18:46 UTC, carakas commented
Thanks for updating @jacob-v-dam, I'll review it this weekend

2023-07-26 19:44 UTC, jacob-v-dam commented
> Thanks for updating @jacob-v-dam, I'll review it this weekend

That would be perfect! The next step is to jump to Symfony 5.4 which is LTS for now.

2023-07-31 18:48 UTC, carakas approved these changes

2023-07-31 18:49 UTC, merged